name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # required for npm provenance
  contents: write # required to push version commits and tags
  pull-requests: write # required for changesets to open version PRs

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run setup
        uses: ./.github/actions/setup

      - name: Configure npm token
        run: pnpm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create release PR or publish to npm
        uses: changesets/action@v1
        with:
          version: pnpm run version
          publish: pnpm run release
          commit: "ci: version packages"
          title: "ci: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
